VIP.com: com.achievo.vipshop
Browser: com.android.browser
Calendar: com.android.calendar
Camera: com.android.camera
Contacts: com.android.contacts
Clock: com.android.deskclock
Email: com.android.email
File Manager: com.android.fileexplorer
Download Manager: com.android.providers.downloads.ui
Settings: com.android.settings
Voice Recorder: com.android.soundrecorder
Themes & Wallpapers: com.android.thememanager
AutoNavi Map: com.autonavi.minimap
Baidu Map: com.baidu.BaiduMap
Baidu Search: com.baidu.searchbox
WPS Office: cn.wps.moffice_eng
Dianping: com.dianping.v1
Universal Remote: com.duokan.phone.remotecontroller
Reader: com.duokan.reader
Alipay: com.eg.android.AlipayGphone
Doupo: com.larus.nova
Health: com.mi.health
Wallet: com.mipay.wallet
Calculator: com.miui.calculator
Compass: com.miui.compass
Gallery: com.miui.gallery
Mi Switch: com.miui.huanji
Services & Feedback: com.miui.miservice
Notes: com.miui.notes
Music: com.miui.player
Screen Recorder: com.miui.screenrecorder
Security Center: com.miui.securitycenter
Video: com.miui.video
Global Internet: com.miui.virtualsim
Xiaoai Assistant: com.miui.voiceassist
Weather: com.miui.weather2
News: com.netease.newsreader.activity
IQIYI: com.qiyi.video
Quark Browser: com.quark.browser
Meituan: com.sankuai.meituan
Weibo: com.sina.weibo
Sogou Input Method: com.sohu.inputmethod.sogou
Watermelon Video: com.ss.android.article.video
Suning Easy Buy: com.suning.mobile.ebuy
Taobao: com.taobao.taobao
WeChat: com.tencent.mm
Tencent Video: com.tencent.qqlive
Game Center: com.xiaomi.gamecenter
Xiaomi Finance: com.xiaomi.jr
Xiaomi App Store: com.xiaomi.market
Scan: com.xiaomi.scanner
Xiaomi Mall: com.xiaomi.shop
Mi Home: com.xiaomi.smarthome
Xiaomi Community: com.xiaomi.vipaccount
Ximalaya FM: com.ximalaya.ting.android
Pinduoduo: com.xunmeng.pinduoduo
Zhihu: com.zhihu.android
Idle Fish: com.taobao.idlefish
Xiaohongshu: com.xingin.xhs
Railway 12306: com.MobileTicket
SMS: com.android.mms
JD: com.jingdong.app.mall