唯品会: com.achievo.vipshop
浏览器: com.android.browser
日历: com.android.calendar
相机: com.android.camera
联系人: com.android.contacts
时钟: com.android.deskclock
邮箱: com.android.email
文件管理: com.android.fileexplorer
短信: com.android.mms
下载管理: com.android.providers.downloads.ui
设置: com.android.settings
录音机: com.android.soundrecorder
主题壁纸: com.android.thememanager
高德地图: com.autonavi.minimap
百度地图: com.baidu.BaiduMap
百度搜索: com.baidu.searchbox
WPS Office: cn.wps.moffice_eng
大众点评: com.dianping.v1
万能遥控: com.duokan.phone.remotecontroller
阅读: com.duokan.reader
支付宝: com.eg.android.AlipayGphone
豆包: com.larus.nova
健康: com.mi.health
钱包: com.mipay.wallet
计算器: com.miui.calculator
指南针: com.miui.compass
相册: com.miui.gallery
小米换机: com.miui.huanji
服务与反馈: com.miui.miservice
便签: com.miui.notes
音乐: com.miui.player
屏幕录制: com.miui.screenrecorder
安全中心: com.miui.securitycenter
视频: com.miui.video
全球上网: com.miui.virtualsim
小爱同学: com.miui.voiceassist
天气: com.miui.weather2
新闻: com.netease.newsreader.activity
爱奇艺: com.qiyi.video
夸克: com.quark.browser
美团: com.sankuai.meituan
微博: com.sina.weibo
搜狗输入法: com.sohu.inputmethod.sogou
西瓜视频: com.ss.android.article.video
苏宁易购: com.suning.mobile.ebuy
淘宝: com.taobao.taobao
微信: com.tencent.mm
腾讯视频: com.tencent.qqlive
58同城: com.wuba
游戏中心: com.xiaomi.gamecenter
小米金融: com.xiaomi.jr
小米应用市场: com.xiaomi.market
扫一扫: com.xiaomi.scanner
小米商城: com.xiaomi.shop
米家: com.xiaomi.smarthome
小米社区: com.xiaomi.vipaccount
喜马拉雅FM: com.ximalaya.ting.android
拼多多: com.xunmeng.pinduoduo
知乎: com.zhihu.android
闲鱼: com.taobao.idlefish
小红书: com.xingin.xhs
铁路12306: com.MobileTicket